# Generated by Django 2.2.16 on 2021-04-14 09:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('rank', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='名次')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScoreRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_port', models.CharField(max_length=128, verbose_name='客户端口')),
                ('grade', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(1)], verbose_name='分数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo1.Users', verbose_name='客户')),
            ],
            options={
                'verbose_name': '分数登记表',
                'verbose_name_plural': '分数登记表',
            },
        ),
    ]
